import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

// components
import SiteHeader from "../components/site-header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Background image container */}
        <div
          className="fixed inset-0 z-0"
          style={{
            backgroundImage: 'url("/string.jpg")', // Replace with your image path
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
          }}
        >
          {/* Optional overlay for better text readability */}
          <div className="absolute inset-0 bg-black/50" />
        </div>

        {/* Header */}
        <header className="relative z-10">
          <SiteHeader />
        </header>

        {/* Main content */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  )
}
